### ISSUE TITLE
Two thermostat setup

### ISSUE THREAD

**Issue by likemondays** [Vortec4800/homebridge-ecobee-away#6]
Hey there :-)

saw the disclaimed limitations, and still installed the plugin. I have an ecobee 3, and an ecobee 4 with multiple sensors.

The switch actually still works - it just sets both thermostats into away mode, whereas I would love for it to be just the upstairs one. The end goal would be to create a simple 'when the last person leaves, set the upstairs thermostat to away' Homekit automation. I can't do that to the downstairs thermostat, as our dog would get extremely hot, ha ;-)

Would love it if you are open utilizing my use case to add a 'by device' type feature.

**Comment by Vortec4800** [comment]
This should be supported now.
